# render.yaml
services:
  - type: web
    name: hola-django
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hola_django.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hola_django.settings
